### ISSUE TITLE
This app sucks

### ISSUE THREAD

**Issue by mapehe** [aleksimyllyoja/git-for-professionals#1]
Hey man just launched this and it commits everything causing the git repo to bloat like crazy.

**Comment by aleksimyllyoja** [comment]
This is not an issue, but a feature. I'm closing this.

**Comment by aleksimyllyoja** [comment]
Actually I'm reopening this, because "this app sucks" is true, and not a feature. The description why this app sucks is still invalid though. Can you @mapehe help make this app not suck?

**Comment by aleksimyllyoja** [comment]
Maybe replace the "asd" commit message with a random Wu Tang verse?

**Comment by mapehe** [comment]
Yeah I think that could improve things significantly

**Comment by akx** [comment]
> random Wu Tang verse

We could employ a suitably trained char-RNN or similar neural network to generate certifiably random verses 🤔

**Comment by aleksimyllyoja** [comment]
Our development team is already gathering the data.

**Comment by aleksimyllyoja** [comment]
https://github.com/aleksimyllyoja/git-for-professionals/commit/4a1bd46444fa0d2c21bf6cf9ecad6fb492b8eda5

Closing this forurper or ya wa mion, my jeat on min
